package UI.Commands

object ExactCommandType extends Enumeration {
  type ExactCommandType = Value
  val EXIT,
  HELP,
  FILELOADER, RANDOMLOADER,
  FILEEXPORTER, OUTPUTEXPORTER,
  DEFAULTCONVERTOR, SEQUENCECONVERTOR, RANGECONVERTOR,
  ROTATEFILTER, SCALEFILTER, INVERTFILTER, FLIPFILTER, BRIGHTNESSFILTER, FIXRATIO
    = Value
}
